version: '3.8'

services:
  frontend:
    build:
      context: ./apps/frontend
      dockerfile: ../../Dockerfile.frontend  
    ports:
      - "3000:3000"
    depends_on:
      - ai-service
    environment:
      - NODE_ENV=production

  ai-service:
    build:
      context: ./packages/ai
      dockerfile: ../../Dockerfile.ai-service
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}

  db:
    image: alpine:latest
    volumes:
      - db_data:/data
    command: ['sh', '-c', 'mkdir -p /data && tail -f /dev/null']

networks:
  default:
    driver: bridge

volumes:
  db_data:
    driver: local
