'use client';

import { GeneratedButton, GeneratedCard } from '@/components/generated';
import { useState } from 'react';

export default function DemoPage() {
  const [clickCount, setClickCount] = useState(0);

  return (
    <div className="min-h-screen bg-gray-50 dark:bg-gray-900 py-12">
      <div className="container mx-auto px-4">
        <div className="text-center mb-12">
          <h1 className="text-4xl font-bold text-gray-900 dark:text-white mb-4">
            AI Generated Components Demo
          </h1>
          <p className="text-xl text-gray-600 dark:text-gray-300">
            Examples of components generated by AI and rendered in real-time
          </p>
        </div>

        <div className="grid grid-cols-1 lg:grid-cols-2 gap-8 max-w-6xl mx-auto">
          {/* Button Demo */}
          <GeneratedCard
            title="Generated Button Component"
            description="Interactive buttons with different variants and sizes"
            variant="elevated"
          >
            <div className="space-y-4">
              <div className="flex flex-wrap gap-3">
                <GeneratedButton 
                  variant="primary" 
                  size="sm"
                  onClick={() => setClickCount(c => c + 1)}
                >
                  Primary Small
                </GeneratedButton>
                <GeneratedButton 
                  variant="secondary" 
                  size="md"
                  onClick={() => setClickCount(c => c + 1)}
                >
                  Secondary Medium
                </GeneratedButton>
                <GeneratedButton 
                  variant="outline" 
                  size="lg"
                  onClick={() => setClickCount(c => c + 1)}
                >
                  Outline Large
                </GeneratedButton>
              </div>
              
              <div className="flex gap-3">
                <GeneratedButton disabled>
                  Disabled Button
                </GeneratedButton>
                <GeneratedButton 
                  variant="primary"
                  onClick={() => setClickCount(0)}
                >
                  Reset Counter
                </GeneratedButton>
              </div>
              
              <div className="p-3 bg-blue-50 dark:bg-blue-900/20 rounded-md">
                <p className="text-sm text-blue-700 dark:text-blue-300">
                  Click count: <span className="font-semibold">{clickCount}</span>
                </p>
              </div>
            </div>
          </GeneratedCard>

          {/* Card Demo */}
          <GeneratedCard
            title="Generated Card Variants"
            description="Different card styles and configurations"
            variant="elevated"
          >
            <div className="space-y-4">
              <GeneratedCard
                title="Default Card"
                description="This is a default card with basic styling"
                variant="default"
              >
                <GeneratedButton size="sm">Learn More</GeneratedButton>
              </GeneratedCard>

              <GeneratedCard
                title="Outlined Card"
                description="This card has an outlined border style"
                variant="outlined"
              >
                <div className="flex gap-2">
                  <GeneratedButton variant="outline" size="sm">
                    Action 1
                  </GeneratedButton>
                  <GeneratedButton variant="secondary" size="sm">
                    Action 2
                  </GeneratedButton>
                </div>
              </GeneratedCard>

              <GeneratedCard variant="default">
                <div className="text-center">
                  <h4 className="font-medium text-gray-900 dark:text-white mb-2">
                    Card without title prop
                  </h4>
                  <p className="text-gray-600 dark:text-gray-300 text-sm">
                    This card demonstrates flexibility in content structure
                  </p>
                </div>
              </GeneratedCard>
            </div>
          </GeneratedCard>

          {/* Interactive Demo */}
          <GeneratedCard
            title="Interactive Component Demo"
            description="Real-time component interaction and state management"
            variant="elevated"
            className="lg:col-span-2"
          >
            <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
              <div className="space-y-3">
                <h4 className="font-medium text-gray-900 dark:text-white">
                  Button Variants
                </h4>
                <div className="space-y-2">
                  <GeneratedButton 
                    variant="primary" 
                    className="w-full"
                    onClick={() => setClickCount(c => c + 1)}
                  >
                    Primary (+1)
                  </GeneratedButton>
                  <GeneratedButton 
                    variant="secondary" 
                    className="w-full"
                    onClick={() => setClickCount(c => c + 2)}
                  >
                    Secondary (+2)
                  </GeneratedButton>
                  <GeneratedButton 
                    variant="outline" 
                    className="w-full"
                    onClick={() => setClickCount(c => c + 3)}
                  >
                    Outline (+3)
                  </GeneratedButton>
                </div>
              </div>

              <div className="space-y-3">
                <h4 className="font-medium text-gray-900 dark:text-white">
                  Button Sizes
                </h4>
                <div className="space-y-2">
                  <GeneratedButton 
                    size="sm" 
                    className="w-full"
                    onClick={() => setClickCount(c => c + 1)}
                  >
                    Small Size
                  </GeneratedButton>
                  <GeneratedButton 
                    size="md" 
                    className="w-full"
                    onClick={() => setClickCount(c => c + 1)}
                  >
                    Medium Size
                  </GeneratedButton>
                  <GeneratedButton 
                    size="lg" 
                    className="w-full"
                    onClick={() => setClickCount(c => c + 1)}
                  >
                    Large Size
                  </GeneratedButton>
                </div>
              </div>

              <div className="space-y-3">
                <h4 className="font-medium text-gray-900 dark:text-white">
                  Current State
                </h4>
                <div className="p-4 bg-gradient-to-br from-green-50 to-blue-50 dark:from-green-900/20 dark:to-blue-900/20 rounded-lg">
                  <div className="text-center">
                    <div className="text-3xl font-bold text-green-700 dark:text-green-300 mb-1">
                      {clickCount}
                    </div>
                    <div className="text-sm text-gray-600 dark:text-gray-400">
                      Total Clicks
                    </div>
                  </div>
                  <GeneratedButton 
                    variant="outline"
                    size="sm"
                    className="w-full mt-3"
                    onClick={() => setClickCount(0)}
                  >
                    Reset
                  </GeneratedButton>
                </div>
              </div>
            </div>
          </GeneratedCard>
        </div>

        {/* Code Preview Section */}
        <div className="mt-12 max-w-4xl mx-auto">
          <GeneratedCard
            title="Generated Code Preview"
            description="This is how AI-generated components look in code"
            variant="outlined"
          >
            <div className="bg-gray-900 rounded-lg p-4 overflow-x-auto">
              <pre className="text-green-400 text-sm">
                <code>{`// AI Generated Component Example
import { GeneratedButton } from '@/components/generated';

export function MyComponent() {
  return (
    <div>
      <GeneratedButton 
        variant="primary" 
        size="md"
        onClick={() => console.log('Button clicked!')}
      >
        Click Me
      </GeneratedButton>
    </div>
  );
}`}</code>
              </pre>
            </div>
          </GeneratedCard>
        </div>
      </div>
    </div>
  );
}
